export const GET_COUNTRIES = 'GET_COUNTRIES'; 

export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';

export const GET_ACTIVITIES = "GET_ACTIVITIES";

export const GET_NAME_COUNTRIES ='GET_NAME_CONTRIES';

export const ORDER_BY_NAME = "ORDER_BY_NAME"

export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION"

export const FILTER_CONTINENT = "FILTER_CONTINENT"

export const FILTER_ACTIVITY = "FILTER_ACTIVITY"

export const POST_ACTIVITY = "POST_ACTIVITY"

export const ORDER_NAME_ASC = 'A-Z'
export const ORDER_NAME_DES = 'Z-A'

export const ORDER_HAB_ASC = 'LARGEST'
export const ORDER_HAB_DES = 'LOWEST'